---
- hosts: all
  tasks:

  - name: update package list
    pacman: update_cache=yes
    sudo: yes

  - name: install packages
    pacman: name={{ item }}
    sudo: yes
    with_items:
      - zsh
      - git
      - mercurial
      - the_silver_searcher
      - cmake
      - ninja
      - clang
      - subversion
      - boost
      - /vagrant/ansible/z3-codeplex-4.3.2-1-x86_64.pkg.tar.xz

  # uncomment the following to build z3
  #
  # - name: "add archlinuxfr repository to pacman"
  #   lineinfile:
  #     dest: "/etc/pacman.conf"
  #     line: "{{ item }}"
  #   with_items:
  #     - "[archlinuxfr]"
  #     - "SigLevel = Never"
  #     - "Server = http://repo.archlinux.fr/$arch"
  #   sudo: yes
  #
  # - name: install yaourt
  #   pacman: name=yaourt update_cache=yes
  #   sudo: yes
  #
  # - name: check z3 present
  #   command: pacman -Q z3-codeplex
  #   register: packages_presence
  #   changed_when: False
  #   failed_when: False
  #
  # - name: install z3
  #   command: yaourt -S --noconfirm z3-codeplex
  #   when: packages_presence|failed

  - name: create directories
    file: dest={{ item }} state=directory
    with_items:
      - /home/vagrant/bin
      - /home/vagrant/benchmarks
      - /home/vagrant/src
      - /home/vagrant/results

  - name: checkout svcomp14 benchmarks
    subversion: repo=https://svn.sosy-lab.org/software/sv-benchmarks/tags/svcomp14/
                dest=/home/vagrant/benchmarks/svcomp14

  - name: checkout svcomp15 benchmarks
    subversion: repo=https://svn.sosy-lab.org/software/sv-benchmarks/tags/svcomp15/
                dest=/home/vagrant/benchmarks/svcomp15

  - name: clone llvm
    git: repo=https://github.com/thpani/llvm.git
         dest=/home/vagrant/src/llvm/
         version=patches/release_34_nullsucc

  - name: clone clang
    git: repo=http://llvm.org/git/clang.git
         dest=/home/vagrant/src/llvm/tools/clang/
         version=release_34

  - name: clone clang-tools-extra
    git: repo=https://github.com/thpani/clang-tools-extra.git
         dest=/home/vagrant/src/llvm/tools/clang/tools/extra/

  - name: create llvm-build dir
    file: dest=/home/vagrant/src/llvm-build/ state=directory

  - name: cmake
    command: cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-std=c++11 -I/usr/include/z3 -w" -DLLVM_TARGETS_TO_BUILD="X86" -DCMAKE_BUILD_TYPE=Release -DHAVE_SANITIZER_MSAN_INTERFACE_H=0 -Wno-dev ../llvm/
             chdir=/home/vagrant/src/llvm-build/

  - name: ninja sloopy
    command: ninja sloopy
             chdir=/home/vagrant/src/llvm-build/
