---
- hosts: all
  tasks:

  - name: update package list
    pacman: update_cache=yes
    sudo: yes

  - name: install packages
    pacman: name={{ item }}
    sudo: yes
    with_items:
      - zsh
      - git
      - mercurial
      - the_silver_searcher
      - cmake
      - ninja
      - clang
      - subversion
      - boost

  - name: create directories
    file: dest={{ item }} state=directory
    with_items:
      - /home/vagrant/bin
      - /home/vagrant/benchmarks
      - /home/vagrant/src
      - /home/vagrant/results

  - name: checkout svcomp14 benchmarks
    subversion: repo=https://svn.sosy-lab.org/software/sv-benchmarks/tags/svcomp14/
                dest=/home/vagrant/benchmarks/svcomp14

  - name: checkout svcomp15 benchmarks
    subversion: repo=https://svn.sosy-lab.org/software/sv-benchmarks/tags/svcomp15/
                dest=/home/vagrant/benchmarks/svcomp15

  - name: clone llvm
    git: repo=https://github.com/thpani/llvm.git
         dest=/home/vagrant/src/llvm/
         version=patches/release_34_nullsucc

  - name: clone clang
    git: repo=http://llvm.org/git/clang.git
         dest=/home/vagrant/src/llvm/tools/clang/
         version=release_34

  - name: clone clang-tools-extra
    git: repo=https://github.com/thpani/clang-tools-extra.git
         dest=/home/vagrant/src/llvm/tools/clang/tools/extra/

  - name: create llvm-build dir
    file: dest=/home/vagrant/src/llvm-build/ state=directory

  - name: cmake
    command: cmake -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-std=c++11" -DLLVM_TARGETS_TO_BUILD="X86;CppBackend" ../llvm/
             chdir=/home/vagrant/src/llvm-build/

  - name: ninja sloopy
    command: ninja sloopy
             chdir=/home/vagrant/src/llvm-build/
